name: ContextGitHubVariableExample
on: workflow_dispatch
env:
  localvar: ${{vars.TEST_VAR1}}
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - name: Display Context Variable Information
          run: |
            echo "Context Variable : ${{env.localvar}}"