name: Release

on:
  workflow_dispatch:
    inputs:
        javaversion:
            type: string
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  step2:
    runs-on: ubuntu-latest
    needs: step1
        
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{inputs.javaversion}}
          cache: 'maven'
  step3:
    runs-on: ubuntu-latest
    needs: step1
        
    steps:
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true